name: Run Chrome Tests and Publish Allure & HTML Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  PYTHON_VERSION: '3.10'
  ALLURE_VERSION: '2.35.1'

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip & Install test dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path 'requirements.txt') {
            python -m pip install -r requirements.txt
          } else {
            Write-Host "requirements.txt not found, skipping"
          }
          # Ensure test/reporting packages & driver manager are present
          python -m pip install allure-pytest pytest-html webdriver-manager pytest-rerunfailures

      - name: Create output directories
        shell: pwsh
        run: |
          if (-not (Test-Path allure-results)) { New-Item -ItemType Directory -Path allure-results | Out-Null }
          if (-not (Test-Path allure-report)) { New-Item -ItemType Directory -Path allure-report | Out-Null }
          if (-not (Test-Path report)) { New-Item -ItemType Directory -Path report | Out-Null }
          if (-not (Test-Path site)) { New-Item -ItemType Directory -Path site | Out-Null }

      - name: Run Pytest (Allure results + pytest-html; retry flaky tests once)
        shell: pwsh
        run: |
          # This run calls your conftest.py which creates a Chrome instance and maximizes the window.
          # --reruns 1 will retry a single transient test failure automatically.
          python -m pytest --alluredir=allure-results --html=report/pytest-report.html --self-contained-html -v --maxfail=1 --disable-warnings --reruns 1 --reruns-delay 2

      # Upload allure-results (helpful for debugging and consumed by the next action)
      - name: Upload allure-results artifact (temporary)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Debug listing after pytest
        shell: pwsh
        run: |
          Write-Host "Workspace root:"
          Get-ChildItem -Force | Format-Table
          Write-Host "Allure results contents (top):"
          if (Test-Path allure-results) { Get-ChildItem -Recurse allure-results | Select-Object FullName,Length | Format-Table -AutoSize } else { Write-Warning "allure-results missing" }
          Write-Host "pytest-html report:"
          if (Test-Path report) { Get-ChildItem -Recurse report | Select-Object FullName,Length | Format-Table -AutoSize } else { Write-Warning "report folder missing" }

      - name: Generate Allure HTML using andgineer action
        uses: andgineer/allure-report@v3
        with:
          results: 'allure-results'     # folder containing Allure results
          report-path: 'allure-report'  # output path for generated site

      - name: Verify generated Allure report files
        shell: pwsh
        run: |
          Write-Host "Checking generated allure-report folder..."
          if (Test-Path allure-report) {
            Get-ChildItem -Recurse allure-report | Select-Object FullName,Length | Format-Table -AutoSize
          } else {
            Write-Error "allure-report not found (generation failed)"
            exit 1
          }
          if (-not (Test-Path allure-report\data) -or ((Get-ChildItem -Recurse allure-report\data | Measure-Object).Count -eq 0)) {
            Write-Error "allure-report/data is missing or empty; generation failed or results were empty"
            exit 1
          } else {
            Write-Host "allure-report/data present and non-empty."
          }

      - name: Fix Allure index base href (make resources load correctly)
        shell: pwsh
        run: |
          $index = Join-Path $PWD 'allure-report\index.html'
          if (Test-Path $index) {
            $content = Get-Content -Raw -Path $index
            $new = $content -replace '(?i)(<head\b[^>]*>)', '$1`n    <base href="./">'
            Set-Content -Path $index -Value $new -Encoding UTF8
            Write-Host "Patched allure-report/index.html base href."
          } else {
            Write-Warning "allure-report index.html not found; skipping base href fix"
          }

      - name: Prepare site folder (include both reports)
        shell: pwsh
        run: |
          if (Test-Path site) { Remove-Item -Recurse -Force site }
          New-Item -ItemType Directory -Path site | Out-Null

          if (Test-Path allure-report) {
            New-Item -ItemType Directory -Path site\allure-report | Out-Null
            Copy-Item -Recurse -Force -Path (Join-Path $PWD 'allure-report\*') -Destination (Join-Path $PWD 'site\allure-report')
          } else {
            Write-Warning "allure-report missing; site will not include Allure"
          }

          if (Test-Path report\pytest-report.html) {
            New-Item -ItemType Directory -Path site\pytest-report | Out-Null
            Copy-Item -Path (Join-Path $PWD 'report\pytest-report.html') -Destination (Join-Path $PWD 'site\pytest-report\index.html')
          } else {
            Write-Warning "pytest HTML report missing; site will not include pytest html"
          }

          Get-ChildItem -Recurse site | Select-Object FullName,Length | Format-Table -AutoSize

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload HTML reports
        uses: actions/upload-artifact@v4
        with:
          name: html-reports
          path: |
            allure-report
            report

      - name: Deploy site (Allure + pytest HTML) to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          publish_branch: gh-pages
